title: ScientificGo
email: jack.parkinson@scientificgo.org

description: >-
  Scientific Computing Packages for Go 

baseurl: "" 
url: "http://scientificgo.org" 

github_username:  scientificgo

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-sitemap

    #show_downloads: "false"
google_analytics: UA-116821320-1

